### ISSUE TITLE
Help me solve my issue with ffmpeg-kit

### ISSUE THREAD

**Issue by Dev-Demons** [arthenica/ffmpeg-kit-test#42]
pubspec.yaml setting:
flutter:
  plugin:
    platforms:
      android:
        package: com.arthenica.flutter.ffmpeg
        pluginClass: FlutterFFmpegPlugin
      ios:
        pluginClass: FlutterFFmpegPlugin
      web:
        pluginClass: FlutterFFmpegPlugin
      windows:
        pluginClass: FlutterFFmpegPlugin

my test code:
import 'package:ffmpeg_kit_flutter/ffmpeg_kit.dart';
    FFmpegKit.execute(
            '-i "E:\\0_Projects\\Flutter-ffmpeg\\ffmpegtest\\file1.mp4" -c:v mpeg4 file2.mp4')
        .then((session) async {
      final returnCode = await session.getReturnCode();

      if (ReturnCode.isSuccess(returnCode)) {
        print("this is the success");
        // SUCCESS

      } else if (ReturnCode.isCancel(returnCode)) {
        // CANCEL
        print("this is the cancel");
      } else {
        // ERROR
        print("this is the fail");
      }
    });

my error log:
════════ Exception caught by services library ══════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel flutter.arthenica.com/ffmpeg_kit_event:
MissingPluginException(No implementation found for method listen on channel flutter.arthenica.com/ffmpeg_kit_event)

how to fix this issue?

**Comment by tanersener** [comment]
Sorry, I don't follow. What is the connection between your error and this repository? Do you receive it in one of the test applications?

**Comment by Dev-Demons** [comment]
I will close this issue and reopen in "ffmpeg-kit"
