### ISSUE TITLE
Crashed on iOS app opening

### ISSUE THREAD

**Issue by rabelhmd** [arthenica/ffmpeg-kit-test#45]
**Description**
I tried to run the iOS application but it crashes upon opening.

**Expected behaviour**
I wanted to run & visualize the iOS test app properly.

**Current behaviour**
Crashes on starting the app.

**To Reproduce**
Install the pod and run the app.

**Logs**
[pastebin](https://pastebin.com/CLySTqSJ)

**Environment**

- Platform: `iOS`
- Application Type: `cocoapods`
- Version: `ffmpeg-kit-ios-full (5.1)`
- Source branch: `main`
- Xcode version: `14.0.1 (14A400)`

**Comment by tanersener** [comment]
> Version: v4.5/v4.5.LTS

Have you tried using the latest version?

**Comment by rabelhmd** [comment]
Version: `ffmpeg-kit-ios-full (5.1)`
Source branch: `main`

@tanersener

**Comment by tanersener** [comment]
Oh, you are already using `v5.1`. 

Well, in the [project page](https://github.com/arthenica/ffmpeg-kit) there are similar issues reported. Have you looked at them? Have you tried the solutions given there?
