### ISSUE TITLE
How to use system default font on ios ?

### ISSUE THREAD

**Issue by yly6518** [arthenica/ffmpeg-kit-test#59]
I found some registration methods in the demo, but `/System/Library/Fonts`  seems to be applied on Mac OS. How can iPhone devices use Apple font, such as Ping Fang 

> NSString *resourceFolder = [[NSBundle mainBundle] resourcePath];
 NSDictionary *fontNameMapping = @{@"MyFontName" : @"Doppio One"};
[FFmpegKitConfig setFontDirectoryList:[[NSArray alloc] initWithObjects:resourceFolder, @"/System/Library/Fonts", nil] with:fontNameMapping];

What I mean is that Apple does not directly provide a directory for fonts. When I use subtitle files (such as ass files), the font is set to Ping Fang SC. However, after combining the subtitles and videos, it seems that the font in the video is not Ping Fang SC.
I used the same command on the terminal on MacOS, and the video font is correct. Here are the commands:
`ffmpeg -i input.mp4 -vf ass="123.ass" -y output.mp4`
If I use a custom font, then the output video is correct

**Comment by lishangjing-spec** [comment]
你好，如果使用 Ping Fang SC 会不会不支持 韩文类型字幕？
